.env migration
Mikibot/shardwatcher pull request #1
Opened 2019-07-11 21:40 UTC by Niputi

and updated deps

2019-07-22 05:26 UTC, velddev requested changes
Prod is a built artifact, so it can't go back to the root folder for an env file

2019-07-22 05:26 UTC, velddev commented on src/app.ts
> +    path: "../.env",
Will this also work in prod?

2019-07-22 05:26 UTC, velddev commented on package.json
> +    "@types/dotenv": "^6.1.1",
isn't @types/dotenv a devDependency?

2019-07-22 20:21 UTC, Niputi commented
I should maybe also add docker in this pr

2019-07-23 10:33 UTC, velddev approved these changes

2019-07-23 10:33 UTC, merged

2019-07-23 10:34 UTC, velddev commented
Would recommend doing it in a seperate PR